name: Auto Commit Every 30 Minutes

on:
  schedule:
    - cron: '*/30 * * * *'   # every 30 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Ensures the runner fetches the full history to prevent push errors
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run commit script
        run: |
          echo "Running auto commit script..."
          # The Python script will create the commits with the correct Git identity
          python3 auto_commit.py

      - name: Push changes
        run: |
          # Set identity one last time for the 'git push' command and general safety
          git config user.name "Bishal Ranjit" 
          git config user.email "bishalranjit0606@users.noreply.github.com" 
          
          # Push the changes. '|| true' or '|| echo' handles the case where there are no changes to push gracefully
          git push origin main || echo "No new commits to push"
