# .github/workflows/auto_commit.yml
name: Auto Commit Every 1.5 Hours

on:
  # Schedule: Runs every 1.5 hours (90 minutes).
  # The expression '0 0/1,1 * * *' will NOT work.
  # The correct way is to run it on the hour (0) and then 1.5 hours later (90 minutes, which is 30 minutes past the next hour), and repeat.
  # This pattern (0 and 30 minutes past every odd hour) effectively creates a 90-minute cycle.
  schedule:
    # Runs at the start of hours 0, 3, 6, 9, 12, 15, 18, 21 (every 3 hours)
    # AND 30 minutes past hours 1, 4, 7, 10, 13, 16, 19, 22 (every 3 hours)
    # This combination results in a run every 90 minutes (1.5 hours).
    - cron: '0 0,3,6,9,12,15,18,21 * * *' 
    - cron: '30 1,4,7,10,13,16,19,22 * * *'
  
  # Allows manual triggering from the GitHub Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full history to prevent push errors
          fetch-depth: 0 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Introduce Random Delay (Simulate Human Behavior)
        run: |
          # Sleep for a random number of seconds up to 30 minutes (1800 seconds).
          # This breaks the rigid schedule and makes activity look sporadic.
          MAX_DELAY=1800
          DELAY=$(($RANDOM % $MAX_DELAY))
          echo "Sleeping for $DELAY seconds before running the script..."
          sleep $DELAY

      - name: Run commit script
        run: |
          echo "Running auto commit script..."
          python3 auto_commit.py

      - name: Push changes
        run: |
          # CRITICAL FIX: Set identity to one linked to your GitHub profile 
          # to ensure contributions count toward your graph.
          git config user.name "Bishal Ranjit" 
          git config user.email "bishalranjit0606@users.noreply.github.com" 
          
          # Push the changes. '|| echo' allows the workflow to succeed 
          # gracefully even if there are no new commits to push.
          git push origin main || echo "No new commits to push"
