name: Auto Commit Daily

on:
  schedule:
    - cron: '15 0 * * *'   # 6:00 AM Nepal time (00:15 UTC)
  workflow_dispatch:

permissions:
  contents: write   # ✅ This line gives push permission

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # ✅ Use built-in token

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run commit script
        run: |
          echo "Running auto commit script..."
          python3 auto_commit.py

      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Auto commit via GitHub Actions $(date)" || echo "No changes to commit"
          git push origin main
